#!/bin/bash

echo "🚀 Setting up GitHub repository for Porche Club website..."

# Create a new repository on GitHub (you'll need to do this manually in the browser)
echo "📝 Please follow these steps:"
echo "1. Go to https://github.com/new"
echo "2. Create a new repository named 'porche-club'"
echo "3. Make it public"
echo "4. Don't initialize with README, .gitignore, or license"
echo "5. Copy the repository URL (it will look like: https://github.com/YOUR_USERNAME/porche-club.git)"
echo ""
echo "Once you've created the repository, run the following commands:"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/porche-club.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "Then enable GitHub Pages in the repository settings:"
echo "1. Go to Settings > Pages"
echo "2. Source: Deploy from a branch"
echo "3. Branch: main"
echo "4. Folder: / (root)"
echo "5. Save"
echo ""
echo "After that, run: npm run build"
echo "Then commit and push the dist folder for GitHub Pages" 